# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_rest', '0002_todo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='password',
        ),
    ]
