# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_rest', '0003_remove_todo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
